
number = 38
title = "2025-12"
publish = true


[[article]]
file = "voice.md"
path = "/1102"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1103"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1104"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1105"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1106"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1107"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1108"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1109"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1110"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1111"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1112"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1113"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1114"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1115"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1116"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1117"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1118"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1119"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-18"
publish = true
featured = false
