
number = 38
title = "2025-12"
publish = true


[[article]]
file = "voice.md"
path = "/1102"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1103"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1104"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-12-03"
publish = true
featured = true
