number = 1
title = "2022"

[[article]]
file = "1.md"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "folyd"
cover = ""
pub_date = "2022-11-27"
publish = true
featured = true

[[article]]
file = "2.md"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "folyd"
cover = "/static/the-beatles.png"
pub_date = "2022-11-27"
publish = true
featured = true
