
number = 40
title = "2026-02"
publish = true


[[article]]
file = "voice.md"
path = "/1164"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1165"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1166"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1167"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1168"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1169"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-06"
publish = true
featured = false
