
number = 40
title = "2026-02"
publish = true


[[article]]
file = "voice.md"
path = "/1164"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1165"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1166"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1167"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1168"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1169"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1170"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1171"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1172"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1173"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1174"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1175"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1176"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1177"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1178"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1179"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1180"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-02-17"
publish = true
featured = false
