
number = 39
title = "2026-01"
publish = true


[[article]]
file = "voice.md"
path = "/1133"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1134"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1135"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1136"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1137"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1138"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1139"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1140"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1141"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1142"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1143"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1144"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-12"
publish = true
featured = false
