
number = 39
title = "2026-01"
publish = true


[[article]]
file = "voice.md"
path = "/1133"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1134"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1135"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1136"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1137"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1138"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1139"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1140"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1141"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1142"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1143"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1144"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1145"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1146"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1147"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1148"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1149"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1150"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1151"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1152"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1153"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1154"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1155"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1156"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-24"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1157"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-25"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1158"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-26"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1159"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-01-27"
publish = true
featured = false
