
number = 37
title = "2025-11"
publish = true


[[article]]
file = "voice.md"
path = "/1072"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1073"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1074"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1075"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1076"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1077"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1078"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1079"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1080"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1081"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1082"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1083"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1084"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1085"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1086"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1087"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1088"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1089"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1090"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1091"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1092"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1093"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1094"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-23"
publish = true
featured = false
