
number = 37
title = "2025-11"
publish = true


[[article]]
file = "voice.md"
path = "/1072"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1073"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1074"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1075"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1076"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1077"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1078"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1079"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-11-08"
publish = true
featured = false
